USE springfield;

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_mat_pers(ID_MATRIMONIO)
REFERENCES MATRIMONIOS(ID_MATRIMONIO);

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_fam_pers(ID_FAMILIA)
REFERENCES FAMILIAS(ID_FAMILIA);

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_sexo_pers(ID_SEXO)
REFERENCES SEXO(ID_SEXO);

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_res_pers(ID_LUGAR_RESIDENCIA)
REFERENCES LUGARES(ID_LUGAR);

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_prof_pers(ID_PROFESION)
REFERENCES PROFESIONES(ID_PROFESION);

ALTER TABLE PERSONAJES
ADD FOREIGN KEY fk_lugar_prof_pers(ID_LUGAR_PROFESION)
REFERENCES LUGARES(ID_LUGAR);

ALTER TABLE MASCOTAS
ADD FOREIGN KEY fk_fam_masc(ID_FAMILIA)
REFERENCES FAMILIAS(ID_FAMILIA);

ALTER TABLE LUGARES
ADD FOREIGN KEY fk_ciudad_lugares(ID_CIUDAD)
REFERENCES CIUDADES(ID_CIUDAD);

ALTER TABLE FRASES
ADD FOREIGN KEY fk_pers_frases(ID_PERSONAJE)
REFERENCES PERSONAJES(ID_PERSONAJE);

COMMIT;